### ISSUE TITLE
Failed to lookup view "index"

### ISSUE THREAD

**Issue by XxTopKillerzZ** [shitcorp/discord-bot-dashboard#97]
Hi, 
I'm getting this error in dashboard bot:

Error: Failed to lookup view "index" in views directory "./src/views"
    at Function.render (/discord/meme-bot/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/discord/meme-bot/node_modules/express/lib/response.js:1012:7)
    at app.get (/discord/meme-bot/node_modules/discord-bot-dashboard/modules/app.js:81:11)
    at Layer.handle [as handle_request] (/discord/meme-bot/node_modules/express/lib/router/layer.js:95:5)
    at next (/discord/meme-bot/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/discord/meme-bot/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/discord/meme-bot/node_modules/express/lib/router/layer.js:95:5)
    at /discord/meme-bot/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/discord/meme-bot/node_modules/express/lib/router/index.js:335:12)
    at next (/discord/meme-bot/node_modules/express/lib/router/index.js:275:10)

followed everything
and fixed missing setup information

**Comment by Huskydog9988** [comment]
I’ve see node fail to require stuff in the past, but I doubt this is a related case. Can you try and google around maybe? Check and see if the folder or any of the contents are missing/not in the right structure?

**Comment by julianYaman** [comment]
@XxTopKillerzZ Are you still having this problem?

**Comment by Cy63N70** [comment]
Try this
`  app.set('views', __dirname + '/../src/views');
`

**Comment by Huskydog9988** [comment]
The project has comepletly changed its codease and this is no longer valid.
